language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: chuckedfromspace
  password:
    secure: 34u3HuZEKbk+GP20GlY1c8Os5joqUgDKZJF8niZbHvdVgS/33tjsNn9xLaVArCkZcbeEfkUeGyfiWUrE+J/CKieIxFdKJsS2OJ+VWK73bQIZAz2IxzErxeIk5Qz1r8uEaa1iGVCfPF5egx6I9C6G/PFyhDPnc1/e8IZHTtGEQJsc19BW38EeTywNKL5VzSF0MqaZjpFqkRliDNAOYh3vsIz7jOa1ENiDeqorS/va8bcGlTTw/jDDUCkLvvUYjX4XOsyxdkp8CT/PkfcKEK6J5PXzhm2Z7nvK1YActKdpqXI9otw4ZXO/lvNv2uc5aQ2OjXUZJGNyJ4WAStEftg/WopNO9x4QAQBSucvehUPYv8fC/WZl24y4hHlToCe8ukCpcalj9/JeXLlFtCJT2K+8kzh7oT5QQKyBQuBQBzNHBHIyJyVG47ly3FzbSqJ7aNcwaCJI6T5hdeKWQu0ktcEfj7fe+OEfLovmhq7l6wCfYKyYAyyC1YdUKuKLbn9jn3tropz1TMrq2mPahg8GEqIl8xfyrIcxQEm9SByxJWhjCAHeg/0gPbNTaLo25AX9S7rD2ssB7plSZc1y61f6dhSMvRC9o+jIMy9m0Oh6eM9WUCGBLa0A9lUImyirddpiUg3qmKderpNvQQRMu5dCfHOKoYl9rrwMvCDYLzfH+u13WeI=
  on:
    tags: true
    repo: chuckedfromspace/carspy
    python: 3.8
