language: python
python:
- 3.9
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password:
    secure:
  on:
    tags: true
    repo: chuckedfromspace/carspy
    python: 3.8
