language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: chuckedfromspace
  password:
    secure: qinkJciwG/xn5cSgEcqARRrI5dYPmcKr4XlK/m+/7W2iG7ryHVAxa1jgidmwl/plKxpOV6NmWTEMaLyRbFx1aUz/+9gmVts9YpXqXjW4VWVwUkqRRmTJv1qXu3NzgIV3AKG1q9FJ6fsMxH+kmnM2+yhwQlR6At9fQ3a6tDfsX3A7YL1udkMAoIdb973iriqp/hidb1rGZg3/1zu5JXqvrk9bifr59yPJInc9+vrlOCSyGnPL1bzNiiBsPv2Y05JlJF4REOfLan8oHBEfrOQ+b3AcBuGrns7SK700t97wzv97FxaiT6LKcSoVqZ5bKDRchEoWktlYS+7zVuz1owQSIsEA2eSexBvofrcO5YMUbVIkO1yBEjsEs9SsN6lYVVOwAmokfXkSChhlyZLVJdo+XJ1tQFDqMNgZWivirgVGQJ0b3IMV70N/V/Oi6O0CSo+KSVqyNEbFZUyMXgS041XfjoysaW8jDUVnUQDv14NWYMnYVBM9cqQrCIveJJ0WRkIrum5Czmkw+YdFSEyni5cv1xDSmVucngq+laAKUS4lXBYDMRN17PsPtdj+Ilj8jLqxMW0nUio0XNT7x4wswVtvJk1G5LMozKVjyXSRBgxGdu8i+aO5AyBUMUT+CJjpERCh8yfRux8Fv/yytC/L2E1DM435Dt64b7DvF88hiUlhgCk=
  on:
    tags: true
    repo: chuckedfromspace/carspy
    python: 3.8
